version: "3"

services:
  mongodb:
    image: mongo
    networks:
      - mongo-mymovies
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mymovies:
    build:
      context: mymovies
    depends_on:
      - mongodb
    networks:
      - mongo-mymovies
      - mymovies-random
    ports:
      - "3000:3000"

  info:
    build:
      context: info
    depends_on:
      - mongodb
    networks:
      - info-random
    ports:
      - "3001:3001"

  random:
    build:
      context: random
    depends_on:
      - info
      - mymovies
    networks:
      - info-random
      - mymovies-random
    ports:
      - "3002:3002"

networks:
  mongo-mymovies:
  info-random:
  mymovies-random:
