version: "3"

services:
  mongodb:
    image: mongo
    networks:
      - mongo-mymovies

  data:
    build: ./data
    depends_on:
      - mongodb
    networks:
      - mongo-mymovies

  mymovies:
    build:
      context: mymovies
    depends_on:
      - mongodb
    networks:
      - mongo-mymovies
      - mymovies-random

  info:
    build:
      context: info
    depends_on:
      - mongodb
    networks:
      - info-random

  random:
    build:
      context: random
    depends_on:
      - info
      - mymovies
    networks:
      - info-random
      - mymovies-random
      - movies-random
    ports:
      - "3002:3002"

  movies:
    build:
      context: movies
    depends_on:
      - random
    networks:
      - movies-random
    ports:
      - "3003:3000"

networks:
  mongo-mymovies:
  info-random:
  mymovies-random:
  movies-random:
